# Generated by Django 2.1.14 on 2021-07-02 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_logs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zhengju',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('content', models.TextField(verbose_name='证据内容')),
                ('number', models.CharField(max_length=6, verbose_name='证据编号')),
                ('hassorted', models.IntegerField(verbose_name='排序序号')),
            ],
            options={
                'verbose_name': '证据列表',
                'verbose_name_plural': '证据列表',
            },
        ),
    ]
